// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WallapopScraper.Persistence;

#nullable disable

namespace WallapopScraper.Persistence.Migrations
{
    [DbContext(typeof(ScraperDbContext))]
    [Migration("20240130183739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("WallapopScraper.Persistence.Model.WorkerConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CardClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkerConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
